-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 17:06:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Colegio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Colegio` ;

-- -----------------------------------------------------
-- Schema Colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Colegio` DEFAULT CHARACTER SET latin1 ;
USE `Colegio` ;

-- -----------------------------------------------------
-- Table `Colegio`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Estudiante` (
  `eid` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `especialidad` VARCHAR(15) NOT NULL,
  `grado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`eid`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `eid_UNIQUE` ON `Colegio`.`Estudiante` (`eid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Colegio`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Clase` (
  `id_Clase` VARCHAR(6) NOT NULL,
  `nombre` CHAR(25) NOT NULL,
  `horario` VARCHAR(7) NOT NULL,
  `aula` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_Clase`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_Clase_UNIQUE` ON `Colegio`.`Clase` (`id_Clase` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Colegio`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Colegio`.`Inscripcion` (
  `registro` INT NOT NULL AUTO_INCREMENT,
  `nombre_clase` VARCHAR(6) NOT NULL,
  `nombre_estudiante` INT NOT NULL,
  `numero_posicion` INT NOT NULL,
  PRIMARY KEY (`registro`),
  CONSTRAINT `nombre_clase`
    FOREIGN KEY (`nombre_clase`)
    REFERENCES `Colegio`.`Clase` (`id_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre_estudiante`
    FOREIGN KEY (`nombre_estudiante`)
    REFERENCES `Colegio`.`Estudiante` (`eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `registro_UNIQUE` ON `Colegio`.`Inscripcion` (`registro` ASC) VISIBLE;

CREATE INDEX `nombre_clase_idx` ON `Colegio`.`Inscripcion` (`nombre_clase` ASC) VISIBLE;

CREATE INDEX `nombre_estudiante_idx` ON `Colegio`.`Inscripcion` (`nombre_estudiante` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
